import "../app/globals.css";
import Navbar from "@/components/Navbar";
import SmoothScroll from "@/components/SmoothScroll";
import { Inter } from "next/font/google";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const sonder = localfont({
  src: [
    {
      path: "../public/fonts/SonderRegular.otf",
    },
  ],
  variable: "--font-sonder",
});

export const metadata = {
  title: "Paramveer Singh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sonder.variable} h-screen`}>
        <SmoothScroll>
          <Navbar />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
